name: Build Static Bash for Android

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # - arch: aarch64
          #   target: aarch64-linux-android
          #   host: aarch64-linux-android
          #   api: 21
          # - arch: arm
          #   target: armv7a-linux-androideabi
          #   host: arm-linux-androideabi
          #   api: 21
          - arch: x86_64
            target: x86_64-linux-android
            host: x86_64-linux-android
            api: 21
          # - arch: x86
          #   target: i686-linux-android
          #   host: i686-linux-android
          #   api: 21

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Bash source
        run: |
          curl -O https://ftp.gnu.org/gnu/bash/bash-5.2.tar.gz
          tar -xzf bash-5.2.tar.gz
          mv bash-5.2 bash-src

      - name: Apply patches
        run: |
          cd bash-src
          shopt -s nullglob
          for p in ../patches/*.patch; do
            patch -p0 < "$p"
          done

      - name: Build Bash
        env:
          TARGET: ${{ matrix.target }}
          HOST: ${{ matrix.host }}
          API: ${{ matrix.api }}
        run: |
          cd bash-src
          
          TOOLCHAIN=$ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64
          
          export AR=$TOOLCHAIN/bin/llvm-ar
          export CC=$TOOLCHAIN/bin/${TARGET}${API}-clang
          export AS=$CC
          export CXX=$TOOLCHAIN/bin/${TARGET}${API}-clang++
          export LD=$TOOLCHAIN/bin/ld
          export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
          export STRIP=$TOOLCHAIN/bin/llvm-strip
          
          export CFLAGS="-static -O2 -Wno-error=implicit-function-declaration"
          export LDFLAGS="-static"

          sed -i 's/-rdynamic//g' configure
          sed -i '/strtoimax/d' Makefile.in
          sed -i -e 's/strtoimax.c strtoumax.c/strtoumax.c/' -e '/strtoimax/d' lib/sh/Makefile.in
          rm -f m4/strtoimax.m4 lib/sh/strtoimax.c

          ./configure \
            --host=${HOST} \
            --enable-static-link \
            --disable-nls \
            --without-bash-malloc \
            --enable-largefile \
            --enable-alias \
            --enable-readline \
            --enable-history \
            --enable-multibyte \
            --enable-job-control \
            --enable-array-variables \
            bash_cv_dev_fd=whacky \
            bash_cv_getcwd_malloc=yes \
            bash_cv_job_control_missing=present \
            bash_cv_sys_siglist=yes \
            bash_cv_func_sigsetjmp=present \
            bash_cv_unusable_rtsigs=no \
            ac_cv_func_getpwent=no \
            ac_cv_func_endpwent=no \
            ac_cv_func_setpwent=no \
            ac_cv_func_strchrnul=no \
            ac_cv_func_mbsnrtowcs=no

          sed -i 's/${LIBOBJDIR}mbschr$U.o ${LIBOBJDIR}strtoimax$U.o/${LIBOBJDIR}mbschr$U.o/' lib/sh/Makefile

          make -j$(nproc)
          make recho zecho printenv xcase
          $STRIP bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bash-${{ matrix.arch }}
          path: |
            bash-src/bash
            bash-src/recho
            bash-src/zecho
            bash-src/printenv
            bash-src/xcase

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Bash source for tests
        run: |
          curl -O https://ftp.gnu.org/gnu/bash/bash-5.2.tar.gz
          tar -xzf bash-5.2.tar.gz
          mv bash-5.2/tests ./tests

      - name: Download Artifact (x86_64)
        uses: actions/download-artifact@v4
        with:
          name: bash-x86_64
          path: bash-bin

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run tests in Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 24
          target: default
          arch: x86_64
          emulator-options: -no-window -gpu swiftshader_indirect -no-audio -no-boot-anim
          disable-linux-hw-accel: false 
          script: |
            set -e

            #curl -sL -o busybox https://busybox.net/downloads/binaries/1.35.0-x86_64-linux-musl/busybox
            cp .github/bin/busybox-1.35.0-x86_64-linux-musl ./busybox

            adb root
            adb wait-for-device
            adb shell setenforce 0
            adb unroot
            adb wait-for-device

            adb shell mkdir -p /data/local/tmp/bin
            adb shell mkdir -p /data/local/tmp/etc
            adb shell mkdir -p /data/local/tmp/usr

            adb push busybox /data/local/tmp/bin/
            adb shell chmod 755 /data/local/tmp/bin/busybox
            adb shell '/data/local/tmp/bin/busybox --install -s /data/local/tmp/bin'
            adb push tests /data/local/tmp/

            adb push bash-bin/bash /data/local/tmp/
            adb push bash-bin/recho /data/local/tmp/
            adb push bash-bin/zecho /data/local/tmp/
            adb push bash-bin/printenv /data/local/tmp/
            adb push bash-bin/xcase /data/local/tmp/
            adb shell chmod 755 /data/local/tmp/bash /data/local/tmp/recho /data/local/tmp/zecho /data/local/tmp/printenv /data/local/tmp/xcase

            adb push bash-bin/bash /data/local/tmp/tests/
            adb push bash-bin/recho /data/local/tmp/tests/
            adb push bash-bin/zecho /data/local/tmp/tests/
            adb push bash-bin/printenv /data/local/tmp/tests/
            adb push bash-bin/xcase /data/local/tmp/tests/
            adb shell chmod 755 /data/local/tmp/tests/bash /data/local/tmp/tests/recho /data/local/tmp/tests/zecho /data/local/tmp/tests/printenv /data/local/tmp/tests/xcase

            adb shell 'cd /data/local/tmp/tests && sed -i -E -e "s@(^|[^a-zA-Z0-9._-])/tmp([^a-zA-Z0-9._]|$)@\1/data/local/tmp\2@g" -e "s@(^|[^a-zA-Z0-9._])/tmp([^a-zA-Z0-9._-]|$)@\1/data/local/tmp\2@g" run-* *.tests *.sub *.right execscript history.list misc/*.tests'
            adb shell 'cd /data/local/tmp/tests && sed -i -E -e "s@(^|[^a-zA-Z0-9._-])/etc([^a-zA-Z0-9._]|$)@\1/data/local/tmp/etc\2@g" -e "s@(^|[^a-zA-Z0-9._])/etc([^a-zA-Z0-9._-]|$)@\1/data/local/tmp/etc\2@g" run-* *.tests *.sub *.right execscript history.list misc/*.tests'
            adb shell 'cd /data/local/tmp/tests && sed -i -E -e "s@(^|[^a-zA-Z0-9._-])/usr([^a-zA-Z0-9._]|$)@\1/data/local/tmp/usr\2@g" -e "s@(^|[^a-zA-Z0-9._])/usr([^a-zA-Z0-9._-]|$)@\1/data/local/tmp/usr\2@g" run-* *.tests *.sub *.right execscript history.list misc/*.tests'
            adb shell 'cd /data/local/tmp/tests && sed -i "s|/bin/sh|/system/bin/sh|g" run-* *.tests *.sub *.right execscript history.list misc/*.tests'
            adb shell 'cd /data/local/tmp/tests && sed -i "s|/bin/echo|/data/local/tmp/bin/echo|g" run-* *.tests *.sub *.right execscript history.list misc/*.tests'
            adb shell 'cd /data/local/tmp/tests && sed -i "s|/bin/rm|/data/local/tmp/bin/rm|g" run-* *.tests *.sub *.right execscript history.list misc/*.tests'
            adb shell 'cd /data/local/tmp/tests && sed -i "s|/bin/cat|/data/local/tmp/bin/cat|g" run-* *.tests *.sub *.right execscript history.list misc/*.tests'
            adb shell 'cd /data/local/tmp/tests && sed -i "s|/usr/bin/printf|/system/bin/printf|g" run-* *.tests *.sub *.right execscript history.list misc/*.tests'

            adb shell 'echo "root:x:0:0:root:/root:/bin/sh" > /data/local/tmp/etc/passwd'
            adb shell 'cd /data/local/tmp/tests && sed -i "s|ln sh a|cp sh a|g" rsh2.sub'
            adb shell 'cd /data/local/tmp/tests && sed -i "s|\[\[ x =~ \\\${bs}x \]\] ; echo \\\$?|[[ x =~ x ]] ; echo \$?|g" cond-regexp3.sub'

            adb shell 'export PATH=/data/local/tmp/bin:$PATH; export TMPDIR=/data/local/tmp; export THIS_SH=/data/local/tmp/bash; cd /data/local/tmp/tests && ../bash run-all' < /dev/null